services:
  web-scraper-php:
    build:
      context: .
      dockerfile: dockerfile.php
    container_name: web-scraper-php
    stdin_open: true
    tty: true
    volumes:
      - .:/web-scraper

  web-scraper-composer:
    build:
      context: .
      dockerfile: dockerfile.composer
    container_name: web-scraper-composer
    volumes:
      - .:/web-scraper
